-- MySQL Script generated by MySQL Workbench
-- Tue May 10 23:19:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema news_analyse_robot_data_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema news_analyse_robot_data_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news_analyse_robot_data_base` DEFAULT CHARACTER SET utf8 ;
USE `news_analyse_robot_data_base` ;

-- -----------------------------------------------------
-- Table `news_analyse_robot_data_base`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_analyse_robot_data_base`.`news` (
  `idnews` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `title` VARCHAR(100) NULL,
  `body` VARCHAR(1000) NULL,
  `ticker_symbol` VARCHAR(10) NULL,
  PRIMARY KEY (`idnews`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_analyse_robot_data_base`.`stockMarketPrices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_analyse_robot_data_base`.`stockMarketPrices` (
  `datetime` DATETIME NOT NULL,
  `USD` FLOAT NULL,
  `MMM` FLOAT NULL,
  PRIMARY KEY (`datetime`),
  UNIQUE INDEX `datetime_UNIQUE` (`datetime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_analyse_robot_data_base`.`predictions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_analyse_robot_data_base`.`predictions` (
  `newsId` INT NOT NULL,
  `mood` ENUM('positive', 'neutral', 'negative') NULL,
  `importance` ENUM('imorant', 'slightly', 'unimportant') NULL,
  `ticker` VARCHAR(10) NULL,
  PRIMARY KEY (`newsId`),
  UNIQUE INDEX `newsId_UNIQUE` (`newsId` ASC) VISIBLE,
  CONSTRAINT `newsID`
    FOREIGN KEY (`newsId`)
    REFERENCES `news_analyse_robot_data_base`.`news` (`idnews`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_analyse_robot_data_base`.`dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_analyse_robot_data_base`.`dictionary` (
  `ticker` VARCHAR(10) NOT NULL,
  `company_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ticker`),
  UNIQUE INDEX `ticker_UNIQUE` (`ticker` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
